version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    env_file:
      - ./env/frontend.env
    stdin_open: true
    tty: true
  # backend:
  #   build:
  #     context: ./amplify/backend/api/personalwebsite
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ./env/backend.env
  #   networks:
  #     - public
  #     - private